package commands

import (
	"fmt"
	"math/rand"
)

var municipalities = []string{
	"City of Abbotsford",
	"City of Armstrong",
	"City of Burnaby",
	"City of Campbell River",
	"City of Castlegar",
	"City of Chilliwack",
	"City of Colwood",
	"City of Coquitlam",
	"City of Delta",
	"City of Fort St. John",
	"City of Kamloops",
	"City of Kelowna",
	"City of Kimberley",
	"City of Langford",
	"City of Langley",
	"City of Maple Ridge",
	"City of Merritt",
	"City of Mission",
	"City of Nanaimo",
	"City of Parksville",
	"City of Pitt Meadows",
	"City of Port Alberni",
	"City of Port Moody",
	"City of Prince George",
	"City of Prince Rupert",
	"City of Quesnel",
	"City of Revelstoke",
	"City of Richmond",
	"City of Salmon Arm",
	"City of Surrey",
	"City of Terrace",
	"City of Trail",
	"City of Vancouver",
	"City of West Kelowna",
	"City of Williams Lake",
	"Corporation of the City of Courtenay",
	"Corporation of the City of Cranbrook",
	"Corporation of the City of Dawson Creek",
	"Corporation of the City of Duncan",
	"Corporation of the City of Enderby",
	"Corporation of the City of Fernie",
	"Corporation of the City of Grand Forks",
	"Corporation of the City of Greenwood",
	"Corporation of the City of Nelson",
	"Corporation of the City of New Westminster",
	"Corporation of the City of North Vancouver",
	"Corporation of the City of Penticton",
	"Corporation of the City of Port Coquitlam",
	"Corporation of the City of Powell River",
	"Corporation of the City of Rossland",
	"Corporation of the City of Vernon",
	"Corporation of the City of Victoria",
	"Corporation of the City of White Rock",
	"Corporation of the District of Central Saanich",
	"Corporation of the District of Coldstream",
	"Corporation of the District of Kent",
	"Corporation of the District of North Cowichan",
	"Corporation of the District of North Vancouver",
	"Corporation of the District of Oak Bay",
	"Corporation of the District of Peachland",
	"Corporation of the District of Saanich",
	"Corporation of the District of Summerland",
	"Corporation of the District of West Vancouver",
	"Corporation of the Township of Esquimalt",
	"Corporation of the Township of Langley",
	"Corporation of the Township of Spallumcheen",
	"Corporation of the Village of Alert Bay",
	"Corporation of the Village of Ashcroft",
	"Corporation of the Village of Burns Lake",
	"Corporation of the Village of Cumberland",
	"Corporation of the Village of Fruitvale",
	"Corporation of the Village of Hazelton",
	"Corporation of the Village of Keremeos",
	"Corporation of the Village of Lumby",
	"Corporation of the Village of Lytton",
	"Corporation of the Village of McBride",
	"Corporation of the Village of Montrose",
	"Corporation of the Village of New Denver",
	"Corporation of the Village of Pouce Coupe",
	"Corporation of the Village of Salmo",
	"Corporation of the Village of Silverton",
	"Corporation of the Village of Telkwa",
	"Corporation of the Village of Warfield",
	"Corporation of the Village of Zeballos",
	"District of 100 Mile House",
	"District of Barriere",
	"District of Chetwynd",
	"District of Clearwater",
	"District of Elkford",
	"District of Fort St. James",
	"District of Highlands",
	"District of Hope",
	"District of Houston",
	"District of Hudson's Hope",
	"District of Invermere",
	"District of Kitimat",
	"District of Lake Country",
	"District of Lantzville",
	"District of Lillooet",
	"District of Logan Lake",
	"District of Mackenzie",
	"District of Metchosin",
	"District of New Hazelton",
	"District of North Saanich",
	"District of Port Edward",
	"District of Port Hardy",
	"District of Sechelt",
	"District of Sicamous",
	"District of Sooke",
	"District of Sparwood",
	"District of Squamish",
	"District of Stewart",
	"District of Taylor",
	"District of Tofino",
	"District of Tumbler Ridge",
	"District of Ucluelet",
	"District of Vanderhoof",
	"District of Wells",
	"Northern Rockies Regional Municipality",
	"Town of Comox",
	"Town of Creston",
	"Town of Gibsons",
	"Town of Golden",
	"Town of Ladysmith",
	"Town of Lake Cowichan",
	"Town of Oliver",
	"Town of Osoyoos",
	"Town of Port McNeill",
	"Town of Princeton",
	"Town of Qualicum Beach",
	"Town of Sidney",
	"Town of Smithers",
	"Town of View Royal",
	"Village of Anmore",
	"Village of Belcarra",
	"Village of Cache Creek",
	"Village of Canal Flats",
	"Village of Chase",
	"Village of Clinton",
	"Village of Daajing Giids",
	"Village of Fraser Lake",
	"Village of Gold River",
	"Village of Granisle",
	"Village of Harrison Hot Springs",
	"Village of Kaslo",
	"Village of Lions Bay",
	"Village of Masset",
	"Village of Midway",
	"Village of Nakusp",
	"Village of Pemberton",
	"Village of Port Alice",
	"Village of Port Clements",
	"Village of Radium Hot Springs",
	"Village of Sayward",
	"Village of Slocan",
	"Village of Tahsis",
	"Village of Valemount",
}

func (h *handler) handleBc() error {
	municipalityIndex := rand.Int() % len(municipalities)
	municipality := municipalities[municipalityIndex]
	message := fmt.Sprintf("Ahh, The %s... capital of British Columbia!", municipality)
	return h.say(message)
}
